### ISSUE TITLE
画像 Caption の検討

### ISSUE THREAD

**Issue by kenzauros** [mseninc/blog-gatsby#1]
WordPress の画像キャプションに使用していた [Caption] に代わるものを検討する

**Comment by k-so16** [comment]
ざっと読んだところ、何通りか実現方法が提案されていましたが、結局 HTML タグで書くのが無難そうでしょうか?

https://thesynack.com/posts/markdown-captions/

**Comment by kenzauros** [comment]
一応プラグインもあるようだ

[gatsby-remark-figure-caption | Gatsby](https://www.gatsbyjs.com/plugins/gatsby-remark-figure-caption/)

**Comment by kenzauros** [comment]
```md
![Amazon Rainforest](/path/to/image)
*The Amazon Rainforest contains a multitude of species.*
```

```html
<p>
	<img src="/path/to/image" alt="Amazon Rainforest">
	<em>The Amazon Rainforest contains a multitude of species.</em>
</p>
```

このタイプでいってみましょうか
