### ISSUE TITLE
ダークモードのレイアウトの調整検討

### ISSUE THREAD

**Issue by k-so16** [mseninc/blog-gatsby#10]
ダークモード時のレイアウトについて調整したほうが良さそうな項目を以下に列挙します。

- リンクの青色が背景の黒色に対して見づらく感じる
- コードブロックの境界線が分かりづらく感じる
- 右上のダークモードのトグルに何らかのアイコンを付与したほうがわかりやすく感じる

**Comment by kenzauros** [comment]
ダークモードのトグルに関してはあまり機能として主張させたくないため、わざとアイコン等は付加していません。
あまり目立たずわかりやすくできそうなデザインがあれば、提案してもらると助かります。

**Comment by kenzauros** [comment]
ダークモードのリンクカラー `#4d9bf3` ぐらいではどうですかね

![image](https://user-images.githubusercontent.com/13431810/133206610-86b188ac-3c0d-4d86-b7de-df01a07be9f8.png)

**Comment by kenzauros** [comment]
コードブロックのテーマについては、現状で Okaidia を採用してますが、これの背景色が結構黒いので一体化しがちですね。

[Prism Demo - Okaidia Theme](https://tutsplus.github.io/syntax-highlighter-demos/prism_okaidia.html)

境界線入れてみたらどうですかね

![image](https://user-images.githubusercontent.com/13431810/133208077-2e404ca9-a1fd-4109-9b54-17113f80bd34.png)

**Comment by k-so16** [comment]
リンクとコードブロックの対応ありがとうございます。
トグルについては目立たない方法で何か良いデザインがないか考えてみます。
