### ISSUE TITLE
記事ページのレイアウト検討

### ISSUE THREAD

**Issue by linkohta** [mseninc/blog-gatsby#11]
記事ページのレイアウトについて、気になった点を列挙しておきます。

- コードのインライン表示が背景真っ黒になっている。
- 全体的に文字が小さく感じる。（？）
- h2 と h3 の判別が付きづらい。
- 目次欄が大きい。

**Comment by kenzauros** [comment]
基本のフォントサイズは 16px なので現代の標準のフォントサイズになっているはずです。
ただ line height が若干狭めかなとは思います。行間のせいですか？

**Comment by linkohta** [comment]
仰る通り、行間が狭いからかもしれません。

ただ、こちらの項目は感覚的なものなのであまり参考にはならないかもしれません。

**Comment by kenzauros** [comment]
いや読者としての感覚は大事なので、それでいいと思います。
Chrome の DevTools などで `line-height` を調整したりして、読みやすくなる行間を探してみるとかしてみてください

**Comment by linkohta** [comment]
承知しました。

**Comment by kenzauros** [comment]
インラインコードのカラーリングと h2 のスタイルを調整してみました

![ss_20210914_160721](https://user-images.githubusercontent.com/13431810/133211433-47d2182d-57be-4bad-a504-31fab76b99ba.png)
![ss_20210914_160737](https://user-images.githubusercontent.com/13431810/133211437-77cf9fbd-3883-48f1-a645-790e24ed10b2.png)

**Comment by linkohta** [comment]
インラインコードは個人的にはこれでいいと思います。

見出しは h2 と h3 の区別が付きづらいのがあまり良くないのではないかと今更ながら思いました。
