### ISSUE TITLE
docker/build-push-action@v3 の仕様変更対応

### ISSUE THREAD

**Issue by kenzauros** [mseninc/blog-gatsby#31]
v2 で `repository` や `registry` などのオプションが削除されている。

- [Release v2.0.0 · docker/build-push-action](https://github.com/docker/build-push-action/releases/tag/v2.0.0)

公式にあるようにいくつかのアクションに分かれたようなので、追加する必要がある。

- [docker/build-push-action: GitHub Action to build and push Docker images with Buildx](https://github.com/docker/build-push-action)
- [docker/login-action: GitHub Action to login against a Docker registry](https://github.com/docker/login-action#github-container-registry)

_Originally posted by @kenzauros in https://github.com/mseninc/blog-gatsby/issues/30#issuecomment-1336355482_

**Comment by kiyoshin** [comment]
今は新しく構築された、ステージング側で評価されてるんですか？

**Comment by kenzauros** [comment]
いや、プレビュー用の Docker イメージを作るやつなので、本番もステージングもないです。

**Comment by kiyoshin** [comment]
あー
なるほど
