### ISSUE TITLE
マークダウン上で数式入力の追加

### ISSUE THREAD

**Issue by Lee-juNu** [mseninc/blog-gatsby#39]
後々ブログを書きながら必要だとも思いますが。
` Mathjax ` を使用しての数式の表現ができればいいかと思います。

[gatsby-mathjax-plugin](https://www.gatsbyjs.com/plugins/gatsby-remark-mathjax/)

数式入力例
```
$x+y=5$

$$
x+y=5
$$
```
$x+y=5$

$$
x+y=5
$$

**Comment by kenzauros** [comment]
あ、TeXで書けるならいいですね
