### ISSUE TITLE
記事検索

### ISSUE THREAD

**Issue by kenzauros** [mseninc/blog-gatsby#8]

**Comment by hiratatsu04** [comment]
すみません、ここで良いか分かりませんが、検索すると以下のように記事の画像が重なっていました。
これは仕様上問題ないでしょうか？

![2022-12-27_13h55_21](https://user-images.githubusercontent.com/13930492/209613502-9a75fd90-a341-45f7-b9d3-5019e9a5bb5d.png)
![2022-12-27_13h55_26](https://user-images.githubusercontent.com/13930492/209613515-1056cdb3-fd4b-479e-9797-9eaef444d8d3.png)

**Comment by kenzauros** [comment]
わお、これはびっくり
